apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
        - args:
            - manager
            - --enable-leader-election
            - "--health-probe-bind-address=:8081"
            - --
            - -v 5
          env:
            - name: RELATED_IMAGE_DEX_OPERATOR
              value: "quay.io/identitatem/dex-operator@sha256:2b13763d838ee90427ab23ad44df53e5dabaf37fa575ba548bd61efecc7bba82"
            - name: RELATED_IMAGE_DEX_SERVER
              value: quay.io/dexidp/dex:v2.28.1
          image: quay.io/identitatem/idp-mgmt-operator:latest
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          name: manager
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 300m
              memory: 500Mi
            requests:
              cpu: 300m
              memory: 500Mi
      serviceAccountName: idp-mgmt-operator-controller-manager
      terminationGracePeriodSeconds: 10
