apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.12.0+git
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
  name: idp-mgmt-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Operator to Manage IDP Configurations at the Multicluster Scale
  displayName: identity configuration management for Kubernetes
  icon:
    - base64data: PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA3MjEuMTUgNzIxLjE1Ij48ZGVmcz48c3R5bGU+LmNscy0xe2ZpbGw6I2RiMzkyNzt9LmNscy0ye2ZpbGw6I2NiMzYyODt9LmNscy0ze2ZpbGw6I2ZmZjt9LmNscy00e2ZpbGw6I2UzZTNlMjt9PC9zdHlsZT48L2RlZnM+PHRpdGxlPlByb2R1Y3RfSWNvbi1SZWRfSGF0QWR2YW5jZWRfQ2x1c3Rlcl9NYW5hZ2VtZW50X2Zvcl9LdWJlcm5ldGVzLVJHQjwvdGl0bGU+PGcgaWQ9IkxheWVyXzEiIGRhdGEtbmFtZT0iTGF5ZXIgMSI+PGNpcmNsZSBjbGFzcz0iY2xzLTEiIGN4PSIzNjAuNTciIGN5PSIzNjAuNTciIHI9IjM1OC41OCIvPjxwYXRoIGNsYXNzPSJjbHMtMiIgZD0iTTYxNC4xMywxMDcsMTA3LDYxNC4xM2MxNDAsMTQwLDM2Ny4wNywxNDAsNTA3LjExLDBTNzU0LjE2LDI0Ny4wNiw2MTQuMTMsMTA3WiIvPjxyZWN0IGNsYXNzPSJjbHMtMyIgeD0iMzMwLjg3IiB5PSIyODAuNiIgd2lkdGg9IjIwMy4xNyIgaGVpZ2h0PSIyMCIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoLTc4LjkgMzkwLjUyKSByb3RhdGUoLTQ0Ljk2KSIvPjxyZWN0IGNsYXNzPSJjbHMtMyIgeD0iMzA2LjYzIiB5PSIxNjcuODMiIHdpZHRoPSIyMCIgaGVpZ2h0PSIyMDQuNDciIHRyYW5zZm9ybT0idHJhbnNsYXRlKC04NS4zMyAxNjIuMjcpIHJvdGF0ZSgtMjUuNDUpIi8+PHJlY3QgY2xhc3M9ImNscy0zIiB4PSIxNjIuOTgiIHk9IjM2NC4xIiB3aWR0aD0iMTk4LjI4IiBoZWlnaHQ9IjIwIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgtNDIuMzkgMzMuNjEpIHJvdGF0ZSgtNi43OSkiLz48cmVjdCBjbGFzcz0iY2xzLTMiIHg9IjI0NS4xIiB5PSI0NTEuNTQiIHdpZHRoPSIyMDAuNjIiIGhlaWdodD0iMjAiIHRyYW5zZm9ybT0idHJhbnNsYXRlKC0xNjMuMDEgNzMzLjI2KSByb3RhdGUoLTgxLjMxKSIvPjxyZWN0IGNsYXNzPSJjbHMtMyIgeD0iNDQzLjg1IiB5PSIzMDMuNzYiIHdpZHRoPSIyMCIgaGVpZ2h0PSIyMDcuMDQiIHRyYW5zZm9ybT0idHJhbnNsYXRlKC0xMDkuOTcgNjM5LjU4KSByb3RhdGUoLTY0LjMpIi8+PGNpcmNsZSBjbGFzcz0iY2xzLTMiIGN4PSI1MDQuMzQiIGN5PSIyMTguODMiIHI9IjQ0LjA4Ii8+PGNpcmNsZSBjbGFzcz0iY2xzLTMiIGN4PSIyNzIuNyIgY3k9IjE3Ny43NSIgcj0iNDQuMDgiLz48Y2lyY2xlIGNsYXNzPSJjbHMtMyIgY3g9IjU0Ny4xMiIgY3k9IjQ1Mi4xNyIgcj0iNDQuMDgiLz48Y2lyY2xlIGNsYXNzPSJjbHMtMyIgY3g9IjE2My42OCIgY3k9IjM4NS44MiIgcj0iNDQuMDgiLz48Y2lyY2xlIGNsYXNzPSJjbHMtMyIgY3g9IjMzMC4yNiIgY3k9IjU2MC43IiByPSI0NC4wOCIvPjxwYXRoIGNsYXNzPSJjbHMtNCIgZD0iTTQ0NC45NCwyNzkuOTIsMjc2LjE5LDQ0OC42N0ExMTkuMzIsMTE5LjMyLDAsMCwwLDQ0NC45NCwyNzkuOTJaIi8+PHBhdGggY2xhc3M9ImNscy0zIiBkPSJNMzc1LjY4LDI0NS43NmExMTkuMzMsMTE5LjMzLDAsMCwwLTk5LjQ5LDIwMi45MUw0NDQuOTQsMjc5LjkyQTExOC44OSwxMTguODksMCwwLDAsMzc1LjY4LDI0NS43NloiLz48L2c+PC9zdmc+
      mediatype: image/svg+xml
  install:
    spec:
      clusterPermissions:
        - rules:
            - apiGroups:
                - ""
              resources:
                - configmaps
                - namespaces
                - secrets
                - serviceaccounts
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - ""
              resources:
                - namespaces
                - secrets
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - ""
                - events.k8s.io
              resources:
                - events
              verbs:
                - create
                - patch
                - update
            - apiGroups:
                - apiextensions.k8s.io
              resources:
                - customresourcedefinitions
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
            - apiGroups:
                - apps
              resources:
                - deployments
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - auth.identitatem.io
              resources:
                - dexclients
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - auth.identitatem.io
              resources:
                - dexclients
                - dexclients/status
                - dexservers
                - dexservers/status
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - cluster.open-cluster-management.io
              resources:
                - managedclusters
                - placementdecisions
                - placements
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - cluster.open-cluster-management.io
              resources:
                - placementdecisions
                - placements
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - cluster.open-cluster-management.io
              resources:
                - placements
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - config.openshift.io
              resources:
                - infrastructures
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - coordination.k8s.io
              resources:
                - leases
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
            - apiGroups:
                - identityconfig.identitatem.io
              resources:
                - authrealms
                - authrealms/status
                - strategies
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - identityconfig.identitatem.io
              resources:
                - authrealms
                - clusteroauths
                - strategies
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - identityconfig.identitatem.io
              resources:
                - authrealms
                - strategies
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - identityconfig.identitatem.io
              resources:
                - strategies/finalizers
              verbs:
                - update
            - apiGroups:
                - identityconfig.identitatem.io
              resources:
                - strategies/status
              verbs:
                - get
                - patch
                - update
            - apiGroups:
                - rbac.authorization.k8s.io
              resources:
                - clusterrolebindings
                - rolebindings
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - rbac.authorization.k8s.io
              resources:
                - clusterroles
                - roles
              verbs:
                - bind
                - create
                - delete
                - escalate
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - view.open-cluster-management.io
              resources:
                - managedclusterviews
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - work.open-cluster-management.io
              resources:
                - manifestworks
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
          serviceAccountName: idp-mgmt-operator-controller-manager
        - rules:
            - apiGroups:
                - ""
              resources:
                - configmaps
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - authorization.k8s.io
              resources:
                - subjectaccessreviews
              verbs:
                - create
            - apiGroups:
                - flowcontrol.apiserver.k8s.io
              resources:
                - prioritylevelconfigurations
                - flowschemas
              verbs:
                - get
                - list
                - watch
          serviceAccountName: idp-mgmt-operator-webhook-service
      deployments:
        - name: idp-mgmt-operator-controller-manager
          spec:
            replicas: 1
            selector:
              matchLabels:
                control-plane: controller-manager
            strategy: {}
            template:
              metadata:
                labels:
                  control-plane: controller-manager
              spec:
                containers:
                  - args:
                      - manager
                      - --enable-leader-election
                      - --
                      - -v 5
                    env:
                      - name: RELATED_IMAGE_DEX_OPERATOR
                        value: quay.io/identitatem/dex-operator@sha256:2b13763d838ee90427ab23ad44df53e5dabaf37fa575ba548bd61efecc7bba82
                      - name: RELATED_IMAGE_DEX_SERVER
                        value: quay.io/dexidp/dex:v2.28.1
                    image: quay.io/identitatem/idp-mgmt-operator:latest
                    imagePullPolicy: Always
                    name: manager
                    resources:
                      limits:
                        cpu: 300m
                        memory: 500Mi
                      requests:
                        cpu: 300m
                        memory: 500Mi
                serviceAccountName: idp-mgmt-operator-controller-manager
                terminationGracePeriodSeconds: 10
        - name: idp-mgmt-operator-webhook-service
          spec:
            replicas: 1
            selector:
              matchLabels:
                control-plane: webhook-service
            strategy: {}
            template:
              metadata:
                labels:
                  control-plane: webhook-service
              spec:
                containers:
                  - args:
                      - webhook
                      - --secure-port=6443
                      - --tls-cert-file=/serving-cert/tls.crt
                      - --tls-private-key-file=/serving-cert/tls.key
                      - -v 5
                    image: quay.io/identitatem/idp-mgmt-operator:latest
                    imagePullPolicy: Always
                    name: webhook
                    resources: {}
                    volumeMounts:
                      - mountPath: /serving-cert
                        name: webhook-secret
                        readOnly: true
                serviceAccountName: idp-mgmt-operator-webhook-service
                terminationGracePeriodSeconds: 10
                volumes:
                  - name: webhook-secret
                    secret:
                      secretName: idp-mgmt-webhook
    strategy: deployment
  installModes:
    - supported: true
      type: OwnNamespace
    - supported: true
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: false
      type: AllNamespaces
  keywords:
    - idp-mgmt-operator
  links:
    - name: identity configuration management for Kubernetes
      url: https://github.com/identitatem
  maintainers:
    - email: acm-contact@redhat.com
      name: Red Hat
  maturity: alpha
  provider:
    name: Red Hat
    url: https://github.com/identitatem
  version: 0.0.1
  webhookdefinitions:
    - admissionReviewVersions:
        - v1beta1
      deploymentName: idp-mgmt-operator-webhook-service
      failurePolicy: Fail
      generateName: admission.identityconfig.identitatem.io
      rules:
        - apiGroups:
            - identityconfig.identitatem.io
          apiVersions:
            - v1alpha1
          operations:
            - CREATE
            - UPDATE
          resources:
            - authrealms
      sideEffects: None
      type: ValidatingAdmissionWebhook
      webhookPath: /apis/admission.identityconfig.identitatem.io/v1alpha1/authrealms
