# Copyright Red Hat
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: idp-mgmt-webhook
  creationTimestamp: null
  name: idp-mgmt-operator-webhook-service
spec:
  ports:
  - port: 443
    targetPort: 6443
  selector:
    control-plane: webhook-service
status:
  loadBalancer: {}
