# Copyright Red Hat

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$' # Push events matching semver tags using offical regex - https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string

name: Create Release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Publish a release tagged image
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      run: |
        export VERSION=${GITHUB_REF##*/}
        export IMG_TAG=${GITHUB_REF##*/}
        make publish
