# Copyright Red Hat

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '(\d+)\.(\d+)\.(\d+)-?([a-zA-Z-\d\.]*)\+?([a-zA-Z-\d\.]*)'

name: Create Release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Publish a release tagged image
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      run: |
        export VERSION=${GITHUB_REF##*/}
        export IMG_TAG=${GITHUB_REF##*/}
        make publish
